### ISSUE TITLE
Create a logo for new mod, "Chem Lib"

### ISSUE THREAD

**Issue by al132mc** [al132mc/al-todo#9]
For 1.14.4 i've created a "Chem Lib" mod that will contain all of the elements, compounds, and a few other items/blocks from Alchemistry 1.12.2 that will be shared between Alchemistry 1.14.4, Alchemistry 2 (which is a separate, more realistic mod I am working on), and be available for pack devs as well who want the elements/chemicals, but not the machines.

I need a logo for this mod. It doesn't need to be anything too fancy though.

**Comment by Kinesis-1** [comment]
![Chem Lib Logo](https://user-images.githubusercontent.com/57001246/67566123-00a8e580-f6f5-11e9-9638-78d9231be143.png)

**Comment by al132mc** [comment]
It looks good for the most part. I'm going to be hosting it on curseforge which means that most of the time people view the logo as a thumbnail, so a few things that should probably be tweaked:
1. It should probably be square
2. The wording should probably be a little bigger
3. The pixel ratio must be exactly be 1:1 to upload to curseforge (this is a minor thing I can fix myself, but this image is 600x599)
![image](https://user-images.githubusercontent.com/39097092/67583685-b71ac380-f711-11e9-8413-1d72ea417fef.png)

**Comment by Kinesis-1** [comment]
![Chem Lib Logo2](https://user-images.githubusercontent.com/57001246/67605306-ffef6e00-f74b-11e9-9d81-54ea598a46f5.png)

**Comment by al132mc** [comment]
That should be good enough, thanks!
